### ISSUE TITLE
Section 'artifactOf' of 'File' is not completely supported by RDF parsers/writers

### ISSUE THREAD

**Issue by xavierfigueroav** [spdx/tools-python#104]
- RDF parsers do not handle 'projectURI' field of 'artifactOf' section.
https://github.com/spdx/tools-python/blob/301d72f6ae57c832c1da7f6402fa49b192de6810/spdx/parsers/rdf.py#L588-L596

- RDF writers do not handle anything in 'artifactOf' section. That section is not being written in RDF files. A way to try it is running `python tv_to_rdf.py ../data/SPDXTagExample.tag result.rdf`

Output file attached:
[result.rdf.txt](https://github.com/spdx/tools-python/files/3109813/result.rdf.txt)

**Comment by meretp** [comment]
Thanks for your issue! 
The field 'artifactOf' is deprecated since version 1.8.4. Is this issue still of interest?

**Comment by nicoweidner** [comment]
`artifactOf` is deprecated since a long time, but for some reason it was never removed. I'd say we close this for now, and potentially reopen if someone convinces us the tools should still be able to handle `artifactOf`.

@goneall Do you know why the property was never dropped, and whether anyone still uses it?

**Comment by goneall** [comment]
> Do you know why the property was never dropped, and whether anyone still uses it?

@nicoweidner I don't know why it hasn't been dropped, but it was deprecated on release 2.0 several years ago, so I doubt you will find very many documents still using this property.  It is probably safe to drop it.

**Comment by nicoweidner** [comment]
Closing this for the time being. If anyone really needs support for `artifactOf`, they will have to raise a new issue (or reopen this one)
