### ISSUE TITLE
SPDX IDs format inconsistencies between file formats

### ISSUE THREAD

**Issue by xavierfigueroav** [spdx/tools-python#105]
RDF and TAG/VALUE file formats have two different ways to write SPDX IDs throughout a SPDX Document (document ID, file ID, annotation ID, package ID, etc).

For RDF files: `[DocumentNamespace|DocumentURI]#[SPDX Identifier]`
For TAG/VALUE files: `[SPDX Identifier]`

A problem comes up when a TAG/VALUE file is written from reading an RDF file: **SPDX IDs will have the format for RDF files**. Moreover, if this behavior is ignored while developing JSON/YAML/XML support, it will spread.

**Comment by Yash-Varshney** [comment]
Hello @xavierfigueroav . I am Interested in this issue and want to make it a part of my proposal.
Can you explain a little bit more about the problem here?
Thanks for your time !!

**Comment by nicoweidner** [comment]
I just tried to reproduce this:
```
tools-python$ convertor -i data/SPDXRdfExample.rdf -o out.tag
```
The input file had rdf-style identifiers, the output file had tag-style identifiers. I will close this as it appears to be fixed already.
