### ISSUE TITLE
spdx is not compatible with python 3

### ISSUE THREAD

**Issue by Abhishek-Dev09** [spdx/tools-python#116]
Description- I am using this spdx as deps in scancode-toolkit .When i running the api `calc_verif_code` is not working properly on Python 3. Its saying `TypeError: Unicode-objects must be encoded before hashing` 
My source code - https://github.com/nexB/scancode-toolkit/blob/develop/src/formattedcode/output_spdx.py#L319

Output - https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=954&view=logs&jobId=0b478794-5af2-5128-0bfd-478dc215772f&taskId=9d724a14-ad4d-5378-78fc-204e55328930&lineStart=4409&lineEnd=4410&colStart=1&colEnd=1

OS- macOS Mojave(10.14.6)
Python version - 3.6.8

Even your latest version that supports py3 is also not available on Pypi.
Please update setup also https://github.com/spdx/tools-python/blob/master/setup.py#L51

Please fix this API(https://github.com/spdx/tools-python/blob/master/spdx/package.py#L246) ASAP , i need Py 2/3 compatible .Thanks

**Comment by pombredanne** [comment]
@Abhishek-Dev09 Thank you for the report ! (As you can see this is a small world and I am also the maintainer here ;) )

**Comment by pombredanne** [comment]
@altendky Thank you ++ for the fix, let me review and merge shortly

**Comment by pombredanne** [comment]
@Abhishek-Dev09  I think this is all fixed now, correct? Can you confirm this?

**Comment by Abhishek-Dev09** [comment]
@pombredanne : Yes, you can close this . but classifier is not updated for python 3.

**Comment by pombredanne** [comment]
Thanks!
