### ISSUE TITLE
Relationships not added (as per SPDX spec-2.1)

### ISSUE THREAD

**Issue by ShubhamKJha** [spdx/tools-python#138]
I've found that relationships are not added as per SPDX spec-v2.1. There was a GSoC project to update SPDX Python libraries, but I believe it didn't add relationships. Correct me if I've overlooked something or it was a decision from the mentors.

**Comment by Yash-Varshney** [comment]
for more details about the data format, cardinality & other issues, pls look into:
[Relationship between spdx elements](https://spdx.github.io/spdx-spec/7-relationships-between-SPDX-elements/)

**Comment by meretp** [comment]
As relationships have been added in the meantime, this issue can be closed. @nicoweidner
