### ISSUE TITLE
Parser throwing exception

### ISSUE THREAD

**Issue by rjb4standards** [spdx/tools-python#154]
PackageName:spdx-tools 
SPDXID: SPDXRef-spdx-tools-0.6.1
PackageSupplier: Person:Ahmed H. Ismail 
PackageVersion: 0.6.1

Is throwing an exception on this spdx SBOM data: https://raw.githubusercontent.com/rjb4standards/REA-Products/master/SAG-DBOMPOC-SBOM.spdx  

Here is the exception I'm seeing: 
<class 'TypeError'> 'builtin_function_or_method' object is not subscriptable <traceback object at 0x000001B8B16DC0C8>

**Comment by rjb4standards** [comment]
I found the culprit for this error too: PackageChecksum must be a single line of text, line: 15
LOOKS LIKE SHA256 not supported, only SHA1 allowed:

15: PackageChecksum: SHA256: aaa5ac584f40fe778013df0aa6544bf157799bd3f608364b451840ed2c8688de

> def checksum_from_sha1(value):
>     """
>     Return an spdx.checksum.Algorithm instance representing the SHA1
>     checksum or None if does not match CHECKSUM_RE.
>     """
>     # More constrained regex at lexer level
>     CHECKSUM_RE = **re.compile("SHA1:\\s*([\\S]+)", re.UNICODE)**
>     match = CHECKSUM_RE.match(value)
>     if match:
>         return **checksum.Algorithm(identifier="SHA1", value=match.group(1))**
>     else:
>         return None

**Comment by meretp** [comment]
related to #185

**Comment by meretp** [comment]
Closing this issue as it should be solved with #311. Please reopen, if this is not the case.
