### ISSUE TITLE
Package requires SHA1 hash but spec does not require it

### ISSUE THREAD

**Issue by njv299** [spdx/tools-python#182]
The SPDX spec for the 'Package Checksum' field does not specify that it _must_ be SHA1, but the current Package class validation logic requires it to be.

This is the relevant part of the spec:  
![image](https://user-images.githubusercontent.com/210219/125990315-bfa8e2a6-a1b5-400d-ab24-d6eecfe53008.png)

And this is the section of the code which is doing improper validation (from package.py):
![image](https://user-images.githubusercontent.com/210219/125990452-1c86fe4f-fa58-49e3-b281-53025f38d837.png)

In my opinion the spec itself should also be relaxed with respect to File Checksum requiring SHA1, but that is an argument for a different venue. I'm guessing that this bug is due to copy-paste from the File class, which rightfully checks for a SHA1 hash.

**Comment by njv299** [comment]
I created [this PR](https://github.com/spdx/tools-python/pull/183) to remove the mentioned code.

**Comment by pombredanne** [comment]
All fixed, merged and released. 
Thanks!
