### ISSUE TITLE
Multiple checksums per entity allowed by spec, but not supported by FIle and Package classes

### ISSUE THREAD

**Issue by njv299** [spdx/tools-python#185]
The SPDX spec allows for multiple checksums to be provided for Packages and Files, but the current Package and File classes only allow a single value to be specified.

See the 'Cardinality' section of the following sections of the spec:
![image](https://user-images.githubusercontent.com/210219/126667436-7b8265e5-cb14-4c7a-b4d7-cf86f2133c3f.png)

![image](https://user-images.githubusercontent.com/210219/126667368-c282f0a8-d1db-4048-b232-cf50125b5c02.png)

**Comment by swinslow** [comment]
Just adding a note here, from the SPDX Docfest on Sept. 16 -- looks like this issue leads to errors for valid SPDX documents if they include a `FileChecksum` with the mandatory SHA1, together with additional optional `FileChecksum`s such as SHA256.

**Comment by dholth** [comment]
I began working on this in https://github.com/dholth/tools-python/commit/671986d7ec971b27ff7705740f3a2f3f9204c988

The old `chk_sum` is now a getter that returns the first element of `checksums`, but there is no serialization support as yet.

**Comment by dholth** [comment]
https://github.com/spdx/tools-python/pull/197 can serialize multiple checksums. Parsing them back in is additional work.
