### ISSUE TITLE
Fix output handling with filesAnalyzed

### ISSUE THREAD

**Issue by pombredanne** [spdx/tools-python#193]
This is a follow up to the closed PR https://github.com/spdx/tools-python/pull/192 by @lhh so we can have a discussion on the issue here.

The two commits messages were:
- Include filesAnalyzed in machine-readable output 82be1b3

- Fix filesAnalyzed handling f2a13d6
When filesAnalyzed is False, several sections should be omitted
when omitting rather than being presented as empty sets or "None"
SPDX 2.2, sec:
  3.8.3 - files analyzed specification
  3.9.3 - verification code
  3.14.3 - licenses from files

**Comment by armintaenzertng** [comment]
Closing this issue as it seems the discussion is done by now. Please speak up if it should be reopened.
