### ISSUE TITLE
Release on Pypi

### ISSUE THREAD

**Issue by pombredanne** [spdx/tools-python#2]
The `spdx` name is taken by @bbqsrc which is OK, we can pick `spdx-tools` instead. 
But to avoid namespace issues, either we should find a way to share the namespace (see https://github.com/bbqsrc/spdx-python/issues/1 ) or refactor the namespace used here.

**Comment by sschuberth** [comment]
Thanks @pombredanne for creating https://pypi.python.org/pypi/spdx-tools/, so I guess this can be closed.

**Comment by pombredanne** [comment]
Yes!

**Comment by pombredanne** [comment]
For reference to release on Pypi (using my cached Pypi credentials) I do:
`python setup.py pypi_release`
