### ISSUE TITLE
Fix relationships on non TV output formats

### ISSUE THREAD

**Issue by tamari-oz** [spdx/tools-python#206]
In 0.7.0a3 relationships are only working on TV. Following my change the lib will generate them on other formats.

**Comment by tamari-oz** [comment]
Fix is part of [PR](https://github.com/spdx/tools-python/pull/207)

**Comment by meretp** [comment]
fixed with #270

**Comment by meretp** [comment]
Since the output of the rdf writer for relationships doesn't completely match the spec I will leave this issue open.

**Comment by armintaenzertng** [comment]
The refactored version now found on main should address all issues regarding relationships. Please open a new issue if you find any problems with it.
