### ISSUE TITLE
Invalid `<SpdxDocument>` tags in xml format

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#240]
The [current implementation](https://github.com/spdx/tools-python/blob/a76ded116489be3a06b056f3e1f9d01abce23748/spdx/parsers/xmlparser.py#L53) expects an SPDX document in xml format to be wrapped in `<SpdxDocument>` _and_ `<Document>` tags.

As can be seen [here](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXXMLExample-v2.3.spdx.xml), for example, only `<Document>` tags are necessary anymore.

**Comment by meretp** [comment]
fixed with #254
