### ISSUE TITLE
Support multiple packages per document

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#241]
I came across [this line](https://github.com/spdx/tools-python/blob/7b9395589d65c117f541dc43e85895e2f6fb63ee/spdx/parsers/jsonyamlxml.py#L1654) in the code of `jsonyamlxml.py`:
```
# At the moment, only single-package documents are supported, so just the last package will be stored.
```
Multiple packages per document are supported now, though, so something probably has to be fixed here.

**Comment by meretp** [comment]
This comment has since been deleted and as you say, support for multiple packages is available. I think this was just a leftover comment that noone has taken care of, so I would consider this issue resolved and close it.

**Comment by armintaenzertng** [comment]
yes please :)
