### ISSUE TITLE
json/yaml/xml writer lists all packages in "documentDescribes"

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#242]
In the current [implementation](https://github.com/spdx/tools-python/blob/c0aa92a3a4779fe189c72b5e1d85a18267f6e45a/spdx/writers/jsonyamlxml.py#L480) all packages are written to the "documentDescribes"-Tag. According to the [JSON-example](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json), packages should be listed in a tag "packages" and "documentDescribes" should only contain the SPDXIDs from the objects that the document describes.

**Comment by jasinner** [comment]
Isn't this a duplicate of https://github.com/spdx/tools-python/issues/184 ?

**Comment by jasinner** [comment]
Actually I'm starting to wonder what is the correct use of documentDescribes. In the examples directory for the spec documentDescribes seems to only include some files and packages. Only those which are directly related to the SPDX-Document object in the relationships? There are other packages and files present in the respective packages and files lists which are not listed in documentDescribes. Those seem to be children of the 'top-level packages and files.

**Comment by goneall** [comment]
> Actually I'm starting to wonder what is the correct use of documentDescribes. 

I just went back and looked through the spec and I didn't see a very good definition or description.  Probably something that needs to be addressed.

From some of the SPDX meetings I've been involved in, documentDescribes is intended to be the primary packages and/or files the document is intended to document (or describe).  This gives the consumer of the SPDX document a starting point(s) for traversing the graph of relationships.  In many cases documentDescribes will point to a single package as the root of a tree of relationships.  Other files/packages/snippets within the documents will have some direct or indirect relationship to the described package.

**Comment by nicoweidner** [comment]
I definitely agree that there is no clear description anywhere (as is the case for all specialties of the json format).

My understanding, on a working level, was that: In json (and yaml and xml), all relationships of type `SPDX-Document DESCRIBES SPDX-Element` (where element can be a package, file or snippet) are omitted from the relationships list, and the corresponding spdx ids (of the elements) are instead listed in `documentDescribes`.

Do you agree with that statement, @goneall ? This is coming up in various PRs, so it would be super helpful to have at least a semi-official statement on how it should work :sweat_smile:

**Comment by nicoweidner** [comment]
Just looked at some examples in tools-java: The 2.2 json example has duplicated relationships, i.e.: The elements which are listed in `documentDescribes` appear again as `DESCRIBES` relationships: https://github.com/spdx/tools-java/blob/92e1c5d29eacb0081139b0c05e5e6270b231788c/testResources/SPDXJSONExample-v2.2.spdx.json#L245-L256
In the 2.3 json example, this duplication does not appear.

@goneall Are you aware of any changes between the two versions, or is this unintentional?

**Comment by goneall** [comment]
> Are you aware of any changes between the two versions, or is this unintentional?

This was an intentional change - they were related to the discussion in this issue: https://github.com/spdx/spdx-spec/issues/704

**Comment by nicoweidner** [comment]
We discussed the following strategy for dealing with `documentDescribes`:

**Parsing**:
Read both the relationships in the input document as well as the contents of `documentDescribes`. In the latter case, only add a relationship if no identical relationship exists already (i.e.: Handle the case where a document contains both the relationship as well as the `documentDescribes` entry).

**Writing**:
If a relationship of type `SPDX-doc DESCRIBES SPDX-element` is present and _does not have a comment_, replace it by the corresponding id entry in `documentDescribes`. If the relationship has a comment, however, add both the `documentDescribes` entry and the relationship.

In the weird case of a `SPDX-doc DESCRIBES SPDX-element` with a comment, there is no great solution, and this seemed a reasonable one. The relationship cannot be dropped without losing the comment, and _not_ writing a `documentDescribes` entry would greatly diminish the value of that field.
@goneall @maxhbr Happy to hear comments if you disagree.

**Comment by goneall** [comment]
@nicoweidner Agree with the approach - it is unlikely we're run into relationship comments on a document describes, but if we do you are already handling the duplications on read.

An alternative approach would be to add the describes relationship comment to an Annotation at the document level to preserve the comment - but I think your proposal is a better approach than using the annotations.

**Comment by meretp** [comment]
Fixed with #254
