### ISSUE TITLE
check if namespace can be deleted in SPDXIDs

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#251]
In many places the parsed values are split at `#` to delete the namespace, e.g. [here](https://github.com/spdx/tools-python/blob/2f4225c5a2eb2d1ee577c53b3b6075c91b0981c1/spdx/parsers/rdf.py#L340). This probably originates from the rdf parser, but this is also done in the [jsonyamlxml-writer](https://github.com/spdx/tools-python/blob/2f4225c5a2eb2d1ee577c53b3b6075c91b0981c1/spdx/writers/jsonyamlxml.py#L55-#L56). As mentioned in #247 it should be validated if the part before `#`really is the namespace so that this part is not blindly regarded. 
Related to that it would make sense to check that the namespace is deleted while parsing the file so that only the "raw" values occur in the internal data model and it is no longer required to split values while writing.

**Comment by armintaenzertng** [comment]
Also, the namespace should only be discarded if it actually matches the document namespace. If it is different (i.e. referencing an external element from another document) we have to keep it.

**Comment by zvr** [comment]
As @armintaenzertng wrote, this is really not a _validation_ -- it's a check to see whether the namespace can be deleted as a shorthand.

**Comment by meretp** [comment]
related to #105

**Comment by armintaenzertng** [comment]
This is fixed in the refactored version now found on main.
