### ISSUE TITLE
fix example files

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#256]
The current example files aren't valid according to spec and need some fixes. Below is a list of comments from PR #254 where some of the issues were found.

**Comment by meretp** [comment]
https://github.com/spdx/tools-python/pull/254#discussion_r1006747120
https://github.com/spdx/tools-python/pull/254#discussion_r1006760508

**Comment by armintaenzertng** [comment]
Invalid example files have been removed in the refactored version now found on main.
