### ISSUE TITLE
Fix LicenseInfoInSnippet property name

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#259]
In the Python tools (including the examples in the repo), the https://spdx.github.io/spdx-spec/v2.3/snippet-information/#96-license-information-in-snippet-field property is named `licenseInfoFromSnippet`. However, as can be seen in the spec, it should be called `licenseInfoInSnippet`.

edit: This also applies to files. The property should be called `licenseInfoInFile`

**Comment by armintaenzertng** [comment]
fixed by #289
