### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#267]
Currently, Appveyor is broken, and supposedly it is not the first time that it's unstable.
Many people consider Github Actions a better CI solution than CircleCI.

For these two reasons, I'd suggest to move all CI checks to Github Actions. It seems to support runners for Linux, MacOS and Windows: https://github.com/actions/runner-images

**Comment by nicoweidner** [comment]
@licquia @pombredanne Thoughts on the move?

**Comment by sschuberth** [comment]
> It appears that the Appveyor checks may have been tied to @sschuberth's Appveyor account, which was recently deleted.

Indeed, sorry for that 😞 @maxhbr just pinged me on the breakage.

> So there is a high chance that those checks are now permanently broken.

They should be gone now. They are no more required checks, and I just deleted the dangling webhook from this repo's settings.

:+1: from moving to GitHub actions (for all platforms).

**Comment by nicoweidner** [comment]
> They should be gone now. They are no more required checks, and I just deleted the dangling webhook from this repo's settings.

Cool, thanks for removing them! We will take this as extra incentive to move to Github Actions quickly :sweat_smile:

**Comment by sschuberth** [comment]
> 👍 for moving to GitHub actions (for all platforms).

Maybe this could help here: https://github.com/actions/importer-issue-ops

**Comment by armintaenzertng** [comment]
fixed by #410
