### ISSUE TITLE
Failed to create an SPDX RDF output if license identifier contains a trailing "+" or later sign

### ISSUE THREAD

**Issue by pombredanne** [spdx/tools-python#27]
This is originally reported by @yadsharaf in https://github.com/nexB/scancode-toolkit/issues/692

**Comment by aviral1701** [comment]
@pombredanne what's the update on this?

**Comment by pombredanne** [comment]
@aviral1701 no update... Help would be muched welcomed!

**Comment by aviral1701** [comment]
@pombredanne  on it.

**Comment by aviral1701** [comment]
@pombredanne could you help me get started with this. Please :)

**Comment by aviral1701** [comment]
I have gone through the code,expect a PR soon.

**Comment by aviral1701** [comment]
@pombredanne How do I duplicate this error?

**Comment by yash-nisar** [comment]
@pombredanne @aviral1701 Since this has been fixed, can we close this ?

**Comment by pombredanne** [comment]
@yash-nisar good point. Closing.
