### ISSUE TITLE
[rdf] add support for snippet byte_range and line_range 

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#274]
#273 adds the fields byte range and line range to the internal data model. The rdf parser/writer need to be updated to also handle these new fields. Once this functionality is added the initially skipped tests in `test_conversion.py` and `test_write_anything.py` should be reactivated. And we should also add validation functions for the new fields, at least for the mandatory byte range field.

**Comment by armintaenzertng** [comment]
Full SPDX 2.3 support is now part of the refactored version found on main.
