### ISSUE TITLE
refactor test_tag_value_parser

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#285]
Arisen from https://github.com/spdx/tools-python/pull/282#discussion_r1020397007. 
For now the `TestParser` in `test_tag_value_parser.py` builds a complete document and parses this completely in every single test (`test_doc`, `test_creation_info`, `test_review`, ..). A better approach would be to either parse the whole document once and then call the subtests or to build minimal uncomplete documents specific for every subtest.

**Comment by armintaenzertng** [comment]
This is fixed in the refactored version that can now be found on the main branch.
