### ISSUE TITLE
New (2022) release

### ISSUE THREAD

**Issue by jayvdb** [spdx/tools-python#302]
The last release was over a year ago.

What is blocking a release?

**Comment by meretp** [comment]
Hi @jayvdb! Thanks for asking. We are still in the process of adding support for 2.3 (as you can track on the board [here](https://github.com/orgs/spdx/projects/3/views/1)). Once all changes are implemented and merged, we will make a release.

**Comment by nicoweidner** [comment]
Release candidate is created: https://github.com/spdx/tools-python/releases/tag/v0.7.0-rc0
A PR is up for release notes that are a bit nicer to read than the autogenerated ones. If no last-minute issues are discovered that we have to fix, we should be able to release next week.

**Comment by nicoweidner** [comment]
Release is out on Github: https://github.com/spdx/tools-python/releases/tag/v0.7.0
I will leave this ticket open until it's on PyPI as well.

**Comment by jayvdb** [comment]
PyPi is still 0.6.1
2022 is nearly gone... ;-)

**Comment by nicoweidner** [comment]
Yeah, lots of drama surrounding the PyPI release. The gist is this: Scancode is a big consumer, and has a [non-pinned dependency](https://github.com/nexB/scancode-toolkit/blob/develop/setup.cfg#L107) on the Python tools. There is no max version or [compatible release clause](https://peps.python.org/pep-0440/#compatible-release) either, so any tools-python release with breaking changes will break scancode - which is something we do _not_ want to do. We do have a few renamings and data structure changes which are breaking, so the PyPI release of tools-python will have to be worked into the scancode release schedule. I don't think it will happen this year, unfortunately.

**Comment by nicoweidner** [comment]
Well, it took a long time, but here we go: https://pypi.org/project/spdx-tools/
:tada:
