### ISSUE TITLE
Refactor CreationInfo in new data model

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#306]
The tag/value spec lists all top-level document properties under `CreationInfo`: https://spdx.github.io/spdx-spec/v2.3/document-creation-information/. The current refactored data model is closer to the json schema and contains only a subset of those properties.
It would be more convenient to have all top-level properties bundled under `CreationInfo` (for example in view of the new parser and validator structure).

**Comment by armintaenzertng** [comment]
closed by #345
