### ISSUE TITLE
get_checksum method of File excepts in case of no checksum

### ISSUE THREAD

**Issue by CsatariGergely** [spdx/tools-python#342]
Get checksum just returns a value from self.checksums instead of checking first if there is a value there with the key of hash_algorithm. This leads to an exception in stead of just returning with None in case of no checksum.

**Comment by nicoweidner** [comment]
Thanks for reporting!
That's not very nice, it should either return `None` if no checksum was found or there needs to be a `has_checksum` method that can be used to check existence of a checksum with the given algorithm first.
