### ISSUE TITLE
Adapt CLI tools for refactored parser/data model/validation/writer

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#383]
With the refactoring on https://github.com/spdx/tools-python/tree/refactor-python-tools, the CLI tools need to be adapted to use the new parsers, data model, validation and writers.

The CLI commands should support a version parameter that can be passed down. It is expected that in the case of 2.2 vs 2.3, it will only affect the validation layer, while 3.0 (once a prototype is implemented) will be a completely separate logical path.

As long as some serialization formats are not supported, a corresponding error message should be shown to the user - together with a reference to the 0.7.0 release.

**Comment by armintaenzertng** [comment]
The CLI now supports all formats and 2.2 and 2.3.
