### ISSUE TITLE
Merge refactor branch back into main

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#384]
A major refactoring of the codebase is currently happening on https://github.com/spdx/tools-python/tree/refactor-python-tools. In order to avoid building up large parallel structures and having to maintain diverging branches, it should be brought back to main as soon as possible. It would also be confusing to new contributors if active development is concentrated on a non-standard branch.

When a suitable maturity of the refactoring is reached is up for debate. One suggestion would be: Once the data model and validation layer is complete, and Json is supported end-to-end (meaning that parser and writer are implemented). If there are opinions that this is not enough as a base for upcoming development and `main` needs to have a richer feature set at all times (even if no release is planned during this transitional period), this issue would be a good place for discussion.

When the merge is done, we should:
- create a new `0.7` branch based on the previous version
- Add a prominent note to the top of the readme, outlining current limitations and providing a link to the 0.7.0 release

**Comment by armintaenzertng** [comment]
fixed by 3f2619c3da8d62aa1966487ac00a4d0512b5a0e7
The previous version can be found at https://github.com/spdx/tools-python/tree/version/v0.7.
