### ISSUE TITLE
PEP8 violations at a few places

### ISSUE THREAD

**Issue by yash-nisar** [spdx/tools-python#40]
While going through the codebase, I've noticed a few PEP8 violations which can be fixed by a static code analysis tool like coala.

**Comment by pombredanne** [comment]
@yash-nisar feel to go through this alright imho as a low priority and small touches at a time.
Remember than PEP8 is not an end of its own though: See https://www.youtube.com/watch?v=wf-BqAjZb8M
And making large format changes to a codebase is fraught with problems for any pending PR and work in progress

**Comment by mzfr** [comment]
@pombredanne Can I work on this? 
I will try to PEP8 only those files that are not currently under any PR or maybe commit one file at once.

**Comment by armintaenzertng** [comment]
Closing this as duplicate of #532
