### ISSUE TITLE
Ignore duplicated relationships while parsing

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#400]
While parsing [this file](https://github.com/spdx/spdx-spec/blob/efa69656db9db4fcc871de563cbbd104fc1e33c3/examples/SPDXJSONExample-v2.3.spdx.json#L111) I noticed that the duplicated `hasFiles` entries lead to duplicated relationships in the data model. We might want to avoid that.

**Comment by meretp** [comment]
fixed with #423
