### ISSUE TITLE
Add yaml and xml parser and writer

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#406]
Now that the json end-to-end workflow exists, we can add yaml and xml support for parsing and writing.

**Comment by armintaenzertng** [comment]
To this end, the json parser has to be restructured, extracting the json-specific part (of loading a json-file) from the more general part of parsing the json-like dictionary.

**Comment by goneall** [comment]
We should also track adding the RDF parser and writer.  I've been getting feedback that it is being missed.

**Comment by armintaenzertng** [comment]
Thanks for the feedback, Gary! :)
(would be great, though, if people would get in direct contact instead of hearing from them through you)
RDF parser and writer are certainly a thing we will have to add, and I will open an issue for this.

In the meantime, the [current release candidate on PyPI](https://pypi.org/project/spdx-tools/0.7.0rc0/) offers RDF support, still.

**Comment by armintaenzertng** [comment]
fixed by #408
