### ISSUE TITLE
implement fixtures for tests on the prototype spdx 3

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#432]
Analoguous to the fixtures in spdx 2.x we also want to use fixtures for the tests of the prototyped model.

**Comment by HarshvMahawar** [comment]
is this issue still open? wanna work on it

**Comment by armintaenzertng** [comment]
This targets the `prototype-spdx-3.0` branch. Are you familiar with the current working state of the SPDX 3.0 model? If yes, go ahead, I have unassigned myself from this issue.

**Comment by HarshvMahawar** [comment]
fixtures as in the sense of having sample documents on which newly formed functions in "prototype model 3.0" can be tested?

**Comment by armintaenzertng** [comment]
Yes, exactly. Basically an analogue of this file: https://github.com/spdx/tools-python/blob/refactor-python-tools/tests/spdx/fixtures.py

**Comment by HarshvMahawar** [comment]
what specific program files do we have to target? and what difference it might have from the fixtures in spdx 2.x? from what I can see there are various class methods, do the fixture file have to be made around those?

**Comment by armintaenzertng** [comment]
Ideally, we have a fixture for every class in this folder: https://github.com/spdx/tools-python/tree/prototype-spdx-3.0/src/spdx3/model.
The difference to the 2.x fixtures is that the classes and class structures have changed in 3.0, but the principle should be very much the same.

**Comment by HarshvMahawar** [comment]
yaa I am working on it but it will take time as my schedule is tight right now

**Comment by armintaenzertng** [comment]
No pressure, I just wanted to know if you still plan to work on it :)

**Comment by armintaenzertng** [comment]
Hi again, any estimation on when you might put a PR up for this? We'll probably need the fixtures as input data for the upcoming serialization efforts.
If you need any help, please reach out!

**Comment by HarshvMahawar** [comment]
Sorry for that, but for me this month was quite hectic due to various
examination. If I find any difficulty I will definitely reach out to you.
Thanks and Regards
HarshvM

**Comment by HarshvMahawar** [comment]
@armintaenzertng What sample details should I put in the creation_info class for testing the classes, also are there any references from where I can know what are the valid sample strings or values that can be used for testing as there are some new variables that have been introduced?

**Comment by armintaenzertng** [comment]
`spec_version = SemVer("3.0.0")` and `data_license = "CC0-1.0` are the only fields where the actual value currently matters. For the rest of the fields just put in something of the correct type. In the case of strings, I often go with something that resembles the variable name, like "creation info comment" for the `comment` field of `CreationInfo`.

There is currently no example data for the newly introduced fields which is why we need these fixtures to actually have some data to work and test with.

**Comment by HarshvMahawar** [comment]
<img width="915" alt="agent" src="https://user-images.githubusercontent.com/114311884/234793430-836bebca-b61b-42ab-9c0d-090060fa322b.png">
Does this sample fixture look okay? If there are any corrects please tell :)

**Comment by armintaenzertng** [comment]
Looks promising! As I said before, please just open a PR, this makes commenting on code much easier! :)

Two remarks from my side:
- `spdx_id` must be a URI in SPDX3, e.g. `https://some.namespace/AgentFixture`.
- Please also use `creation_info_fixture()` for the `CreationInformation` and also fixtures for `HashAlgorithm` (for `verified_using`), and `ExternalIdentifier` and `ExternalReference` for their respective properties.

**Comment by HarshvMahawar** [comment]
are we talking about the fixtures of spdx2.3? but isn't creation_info_fixture() based on version 2.3 so not all the fields of CreationInformation of spdx3 match with the fields of creation_info_fixture()

**Comment by meretp** [comment]
Hi @HarshvMahawar, Armin won't be available next week, so I'll take this one over and try to help here. 
Armin was refering to new fixtures for spdx3. Similar to this [fixture]//github.com/spdx/tools-python/blob/63dc18a65e557cb8d6383c45dba31637540a6aad/tests/spdx/fixtures.py#L48-L57) from spdx2.3 where `actor_fixture` is used to fill the list of `creators` you should use `creation_info_fixture()` (spdx3) to populate the `creation_info` field in the `agent_fixture()` (spdx3). So you first need to implement the `creation_info_fixture()` and then implement the other ones.

**Comment by HarshvMahawar** [comment]
I have created creation_info_fixture, integrity_method_fixture, external_reference_fixture, external_identifier_fixture for populating other classes's fixtures
<img width="767" alt="creat_info" src="https://user-images.githubusercontent.com/114311884/235151518-799584e1-7642-4544-acfb-09aa27460c42.png">

But I am facing two problems as of now, 
1.not able to create fixtures of abstract classes ( error: can't instantiate the abstract class )
<img width="790" alt="inte_met" src="https://user-images.githubusercontent.com/114311884/235153258-549f7668-c4ed-4b4e-9465-8f139117d1af.png">

2.getting input type error for external_ref and external_iden
<img width="783" alt="ext_ref" src="https://user-images.githubusercontent.com/114311884/235153415-f38063fb-dc89-4618-9c92-df6122bf0e19.png">

**Comment by meretp** [comment]
Looks good! 
To your problems: 
1. You don't need to write fixtures for abstract classes. You can use the `hash_fixture` for the `verified_using` field. For now, `Hash` is the only instiable subclass of `IntegrityMethod`, so this is okay. 

2. `ExternalReferenceType` is the enum class, you need to choose a value here, so for example `ExternalReferenceType.SECURITY_ADVISORY`. 

Hope this helps!

**Comment by HarshvMahawar** [comment]
where should this fixture file be finally present?   
in tests/spdx3/model     ?

**Comment by HarshvMahawar** [comment]
I have submitted PR #626 for this issue! can you please look into it and tell me if there are any issues so that I can modify

**Comment by HarshvMahawar** [comment]
@meretp @armintaenzertng can you please into PR #626 and share modifications if there

**Comment by HarshvMahawar** [comment]
What should I do about the software_purpose class in software profile?

**Comment by meretp** [comment]
`SoftwarePurpose` is a new enum to represent the purpose of the software (file / package / snippet). In general you can choose any of the values in the enum. You can also have a look at the tests for file, package and snippet (e.g. [tests/spdx3/model/software/test_file.py](https://github.com/spdx/tools-python/blob/prototype-spdx-3.0/tests/spdx3/model/software/test_file.py)), there we also used example values for these fields.  
For the class itself, so `SoftwarePurpose`, we don't need a fixture.

**Comment by HarshvMahawar** [comment]
yes, definitely that is a much better choice :)

**Comment by HarshvMahawar** [comment]
also,I just had one general doubt (if you have time please look into it, it will be really helpful to me:) ) about spdx documents like assume I have been given an project repo and I have asked to make a spdx_document of that project can you tell me a approach I should follow to achieve this like how should I target this problem, I have few ideas just want to hear your approach.
actually its my GSoC project under software heritage :)

**Comment by armintaenzertng** [comment]
Hi @HarshvMahawar, please let us stay on topic in this issue! I'll write you a reply to your question per email.
Currently, the fixtures for the software profile, especially `Package`, are missing. Are you still working on this? Again, no pressure, I just want to know whether we should expect them from you sometime in the future. Using the new structure I introduced in the last PR, this should hopefully not be as much work as it has been before.

**Comment by HarshvMahawar** [comment]
yes, working on it :)

**Comment by HarshvMahawar** [comment]
There are various fields in software profile classes which are not described in fixture_dicts what should I do about that?

**Comment by armintaenzertng** [comment]
The way to add new fixtures is to add new dicts, a single one per class containing example values of properties that are defined in that class (and not in any superclass). Then add an entry to `FIXTURE_DICTS` of all concrete (i.e. not abstract) classes with the class being the key and the value being the list of all dicts from its superclasses and itself.
[Have a look at `Sbom` for an example](https://github.com/spdx/tools-python/blob/534a0119f597a8cf1e7481d38732b3f13eedcf1a/tests/spdx3/fixtures.py#L313), which is a subclass of `Element`, `ElementCollection`, `Bundle` and `Bom`:
```
Sbom: [ELEMENT_DICT, ELEMENT_COLLECTION_DICT, BUNDLE_DICT, SBOM_DICT]
```
(There is no `BOM_DICT`, as `Bom` defines no new properties.)

**Comment by HarshvMahawar** [comment]
but various new fields like "content_type" in software->file are not present in some classes even though these classes contains most of the fields of software->file. So, how can we stop the induction of unnecessary fields using some classes fict_dict in other?

**Comment by armintaenzertng** [comment]
These are all properties from the classes `Artifact` and `SoftwareArtifact`, which `File` is a subclass of. Their values should be set in `ARTIFACT_DICT`and `SOFTWARE_ARTIFACT_DICT`, respectively.
`File` itself only introduces a single new property `content_type`, so that should look like
```
FILE_DICT = {"content_type": "fileContentType"}
```

**Comment by HarshvMahawar** [comment]
#667 also I am writing fixtures for other profiles too...i'll open PR soon

**Comment by HarshvMahawar** [comment]
dataset class is a subclass of package then also some Package_class fieids are used in its initialization like `package_version` etc

**Comment by HarshvMahawar** [comment]
`Dataset` class is a subclass of package but it has come fields of `Package` class in its initialization like `package_version` etc

**Comment by armintaenzertng** [comment]
This is not unique to the `Dataset` class; have a look a the `__init__` methods of the other classes you have written fixtures for so far.
The reason for having a custom `__init__` and not the auto-generated one from `@dataclass` is stated [here](https://github.com/spdx/tools-python/blob/cb680ccfb252e278ed9ffe23bde42487846c54d0/src/spdx_tools/common/typing/type_checks.py#LL8C7-L8C7).

**Comment by HarshvMahawar** [comment]
oh...ic, it was a nice decision :)

**Comment by armintaenzertng** [comment]
https://github.com/spdx/tools-python/pull/550/commits/b48d7f33079f0645ff5e5aabd1a68102d18d599e added the last fixture missing for `Build`. Thus the issue is completed.
