### ISSUE TITLE
Research for RDF support

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#438]
To add the rdf parser and writer we first want to make some research which rdf package to use. Currently [rdflib](https://pypi.org/project/rdflib/) is used. 
Additionally, we want to make RDF an optional feature (see #147). 

Any recommendations for packages to handle rdf files are welcome, as well as hints on how to make a package optional. It should be possible to install `tools-python` without `rdflib` (if we decide to use this package) and only install this package when needed.

Update: possible hint: [cryptography](https://pypi.org/project/cryptography/) uses optional packages (see [here](https://github.com/pyca/cryptography/blob/07d76445e64653263cdf52a2524738fe131763ac/setup.cfg#L57)). 

subtask of #407

**Comment by zvr** [comment]
I strongly recommend using `rdflib` for RDF support.

I don't understand why it should be made optional (would json and tag-value also be optional?).

RDFlib itself has 3 dependencies and 4 optional ones -- which might be a hint how to deal with optional dependencies: https://github.com/RDFLib/rdflib/blob/main/pyproject.toml#L35-L41

**Comment by maxhbr** [comment]
Hey Alexios, 

we want to make the rdf support optional, since it comes with a huge dependency that prevented some adopters from using this library. Making it optional gives us the best of both worlds. It keeps it lightweight and adds support.

**Comment by meretp** [comment]
Thanks for your recommendation @zvr. As I couldn't find any other package that suits better and in view of the fact that the previous implementation also used `rdflib` and thus could provide a bit of a guideline for me as a "rdf-newbie", I will stick to that package.

**Comment by zvr** [comment]
@maxhbr I've heard this claim before, but I would really like to have some actual data pointing to this _huge dependency_ people refer to.

I provided the link to the RDFlib dependencies above, and the required ones are only three small packages.

**Comment by meretp** [comment]
Due to the dependency on `rdflib` the installation size of `tools-python` grows by about 4 MB. We have now decided to leave this dependency for now and try to reduce the size of `tools-python` overall - not necessarily excusively via `rdflib`. As this is a more general need, I opened an extra issue for this (#454) and this issue can be closed. Please ping, if you disagree.
