### ISSUE TITLE
Fix typo: 'redundent' -> 'redundant'

### ISSUE THREAD

**Issue by yash-nisar** [spdx/tools-python#45]
The files where the word `redundent` has been used are : 
`spdx/parsers/rdf.py` and `spdx/parsers/tagvalue.py`

**Comment by bhavybarca** [comment]
@yash-nisar 
hey, could you merge my pull request
thanks

**Comment by pombredanne** [comment]
We are receiving multiple PRs for s single typo. This doe snot deserve a ticket... so I am closing this now
