### ISSUE TITLE
Supplier name could be NOASSERTION

### ISSUE THREAD

**Issue by spatil00** [spdx/tools-python#464]
Supplier name could be NOASSERTION , if this is not added then code throws exception. 

SPDX specification 2.3  says for supplier tag in package. 

"Use NOASSERTION if:

the SPDX document creator has attempted to but cannot reach a reasonable objective determination;

the SPDX document creator has made no attempt to determine this field; or

the SPDX document creator has intentionally provided no information (no meaning should be implied by doing so)."

Check needs to be added to the rdfbuilder.py in function EntityBuilder

**Comment by spatil00** [comment]
I have fix , how can I contribute to fix this issue ?

**Comment by meretp** [comment]
Hi @spatil00! 
Thanks for the report and the fix, please open a PR for the fix and I will have a look! :)

**Comment by spatil00** [comment]
Hi , I don't have access to create branch , could you please help with that.

**Comment by meretp** [comment]
Sure. You need to fork the repo first (this seems to be missing in the contributing guideline), within your own repository you can create a new branch from main and commit your changes to fix the issue. You can then create a pull request from your branch (in your fork) to the original main branch. 
For more information about forks, see here: https://docs.github.com/en/get-started/quickstart/fork-a-repo 
I hope, this helps. 
I will open an issue to add the fork step to the contributing guideline. Sorry for the circumstances here!

**Comment by spatil00** [comment]
Hi @meretp ,  I have created pull request , I am not able to assign that to you , for review but I think you can help me with further process now. 

https://github.com/spdx/tools-python/pull/475

Thanks & Regards
Sandeep
