### ISSUE TITLE
[Request] Is an empty `licenseInfoFromFiles` and `hasFiles` really an error

### ISSUE THREAD

**Issue by chrisdecker1201** [spdx/tools-python#476]
Hello,

I'm getting an SPDX (in JSON) from a third party where the `licenseInfoFromFiles` and `hasFiles` field of a package is an empty array.

~~~json
{
      "SPDXID" : "SPDXRef-2269-coverlet.collector.3.2.0.nupkg",
      "checksums" : [ {
        "algorithm" : "SHA1",
        "checksumValue" : "0cf7564fcbdee13f6313edd8bc261ca0564a4bf7"
      } ],
      "copyrightText" : "NOASSERTION",
      "description" : "Coverlet is a cross platform code coverage library for .NET, with support for line, branch and method coverage.",
      "downloadLocation" : "https://api.nuget.org/packages/coverlet.collector.3.2.0.nupkg",
      "filesAnalyzed" : false,
      "hasFiles" : [ ],
      "homepage" : "https://github.com/coverlet-coverage/coverlet",
      "licenseConcluded" : "(MIT)",
      "licenseDeclared" : "(MIT)",
      "licenseInfoFromFiles" : [ ],
      "name" : "coverlet.collector.3.2.0.nupkg",
      "originator" : "Organization: tonerdo",
      "packageFileName" : "coverlet.collector.3.2.0.nupkg",
      "supplier" : "Organization: tonerdo",
      "versionInfo" : "3.2.0"
 }
~~~

When I try to parse this with this tool, I'm getting an error. I'm wondering if this is really an error or a bug. I think it should be easy to fix, if this is a bug, but before making any changes I just wanted to be sure.

Thank you 😄

**Comment by meretp** [comment]
I'd say it is more of a bug. `hasFiles` and `licenseInfoFromFiles` are optional fields, so ideally the tags should not appear in the file  if the package has no files and no license info from files. But since this can't always be guaranteed, and in my opinion an empty list conveys the same infromation as if the tag didn't exist, this example should be parsable and not raise an error.

**Comment by chrisdecker1201** [comment]
I will try a Pull Request for that.
