### ISSUE TITLE
After installing spdx-tools from pip not able to find pyspdxtools_convertor tool

### ISSUE THREAD

**Issue by natrajms** [spdx/tools-python#477]
Navigate to https://pypi.org/project/spdx-tools/ and using the link _pip install spdx-tools_ install spdx-tools. After that type pyspdxtools_convertor in a new cmd (Windows OS). we get nothing. Is there something I am missing.

**Comment by armintaenzertng** [comment]
Please mind that these commands are run in bash in the GH Actions workflow.

**Comment by meretp** [comment]
@natrajms We had another look into this issue and couldn't reproduce it using a `venv`. Did you use a `venv` when trying to install this? The command to create a `venv` and install the tools would be the following:
```
python -m venv /path/to/virtual/environment/ 
path\to\environment\Scripts\activate
pip install spdx-tools
```
For more information about virtual environments, see the[ official python documentation].(https://docs.python.org/3/library/venv.html)

**Comment by armintaenzertng** [comment]
I believe this issue is resolved. If there are further things to discuss, please feel free to reopen it.
