### ISSUE TITLE
Add convenience function to extract SPDX elements by their Id

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#487]
Along the lines of
`get_element_from_spdx_id(document: Document, spdx_id: str) -> Union[Package, File, Snippet, None]`

**Comment by HarshvMahawar** [comment]
I would like to work on this issue but as I am new here can you please elaborate this issue and what steps should I take? thank you

**Comment by armintaenzertng** [comment]
Hi @HarshvMahawar, this will be part of the `refactor-python-tools` branch, have a look there! :)
I expect that the method I described above goes into `document_utils.py`.

**Comment by armintaenzertng** [comment]
@HarshvMahawar, sorry for not thinking about this earlier, but you are correct. The refactored version from the `refactor-python-tools` branch is not yet available on PyPI. You have to clone the `refactor-python-tools` into your venv and install it via `pip install .`

**Comment by armintaenzertng** [comment]
Use the `[document_fixture()](https://github.com/spdx/tools-python/blob/refactor-python-tools/tests/spdx/fixtures.py)` for testing purposes. The function yields a fully valid document with a snippet, file and package which you can test the retrieval on.

**Comment by HarshvMahawar** [comment]
by applying the mentioned test on the convenience function I am getting the desired results (attached). Should I open a PR?
<img width="794" alt="pr1" src="https://user-images.githubusercontent.com/114311884/226971527-43bb4641-84fa-463f-af66-d81ac813e4fd.png">

**Comment by armintaenzertng** [comment]
This looks like it works as intended, thanks! :)
And sure, don't be afraid to open PRs!

Three remarks:
First, please try to adhere to PEP8, especially concerning whitespaces (find some examples [here](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)).
Second, the above does not look like a working unit test. It would probably suffice to test on the type of `a` and its `spdx_id`.
Third, please don't use non-descriptive variable names like `a` in the code.

**Comment by HarshvMahawar** [comment]
About the first point yes, I will definitely adhere to PEP8.
also about the variable "a", I just used it to see if the function is working or not by getting the sample document (file, snippet, or package) and spdx_id. It won't be there in the actual code.

**Comment by HarshvMahawar** [comment]
#531 I have opened this PR, please look into it and if there are any issues please tell me so that I can modify
