### ISSUE TITLE
Release 0.7.1

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#496]
There have been a few fixes since 0.7.0 which we want to release as 0.7.1.
Things to do beforehand:

- [x] merge #475 and #481
- [x] check for breaking changes
- [x] test the new code
- [x] beta pre-release
- [x] update changelog
- [x] announce new release

**Comment by ssbarnea** [comment]
Apparently there is a a deprecation warning from today's release of setuptools which requires a patch on this library. I will try to make a PR to fix it.
```
DeprecationWarning: pkg_resources is deprecated as an API
```

**Comment by armintaenzertng** [comment]
0.7.1 is up on PyPI
