### ISSUE TITLE
Allow List with NOASSERTION/ NONE for PackageLicenseInfoFromFiles, LicenseInfoInSnippet and LicenseInfoInFile

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#503]
The fields `PackageLicenseInfoFromFiles` in `Package`, `LicenseInfoInSnippet` in `Snippet` and `LicenseInfoInFile` in `File` can be populated with values like `[MIT, NOASSERTION]`. See [this issue ](https://github.com/spdx/spdx-spec/issues/809) in the spec repo. The current refactored version of the tools doesn't allow this which is a bug.

**Comment by armintaenzertng** [comment]
fixed by #505
