### ISSUE TITLE
Files have no SPDX-License-Identifier

### ISSUE THREAD

**Issue by vargenau** [spdx/tools-python#511]
Let us use our own specification :-)

**Comment by armintaenzertng** [comment]
Reopening this as we should also apply this to the refactored branch.

**Comment by HarshvMahawar** [comment]
what exactly needs to be done in this issue, can you please elaborate, thanks :)

**Comment by vargenau** [comment]
See pull request https://github.com/spdx/tools-python/pull/512/
It was done on the current code.
As stated above, ticket is still open as the same must be applied to the refactored branch.

**Comment by armintaenzertng** [comment]
We plan to completely replace the license text with the license identifier in the refactored branch.
The way I understand it, removing a license text this way is only possible by the creators of the files, so it can't be done by you, @HarshvMahawar, sorry.
