### ISSUE TITLE
Fix Error Message Related to ISO 8601 format for `creationInfo` `created` field

### ISSUE THREAD

**Issue by jspeed-meyers** [spdx/tools-python#529]
When a user provides a SPDX document with a time created field that has a fractional second component of an ISO 8601 datetime, `tools-python` returns an error message similar to this:

`Invalid created value '2023-03-17T19:44:10.259Z' must be date in ISO 8601 format.`

After discussion in issue #527 and https://github.com/spdx/ntia-conformance-checker/issues/95, I believe that `tools-python` does not in fact strictly follow ISO 8601, which allows fractional seconds, and instead follows the [SPDX spec](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field), which does not allow fractional seconds.

To help users follow the format expected by the SPDX spec, @zvr suggested this error message instead:

`Invalid created value '2023-03-17T19:44:10.259Z' is not in "YYYY-MM-DDThh:mm:ssZ" format.`

I'm glad to put in a PR if the maintainers are amenable to this change.

**Comment by armintaenzertng** [comment]
Hi @jspeed-meyers, thanks for the thorough investigation of this issue! By all means, please go ahead and open a PR for this if you like! :)
