### ISSUE TITLE
Document node in RDF output has no unique ID

### ISSUE THREAD

**Issue by RinkeHoekstra** [spdx/tools-python#542]
The RDF writer produces a `SpdxDocument` instance that always has the identifier `http://www.spdx.org/tools#SPDXRef-DOCUMENT`. When merging multiple SPDX documents from across multiple distributions, this means that e.g. all package dependencies, the names, the version, the license, creationInfo etc. will be attached to a single node in the RDF graph.

https://github.com/spdx/tools-python/blob/73f3f462591894cac8ef11e01ebec7e702e33c25/spdx/writers/rdf.py#L987

It makes much more sense to use the `name` of the document to construct an identifier as in this line:

https://github.com/spdx/tools-python/blob/73f3f462591894cac8ef11e01ebec7e702e33c25/spdx/writers/rdf.py#L996

**Comment by armintaenzertng** [comment]
Hi @RinkeHoekstra, thanks for pointing this out! This will be fixed in the upcoming refactored version of these tools, soon to be found on the main branch!
