### ISSUE TITLE
Change print to python3 style in example

### ISSUE THREAD

**Issue by macrovve** [spdx/tools-python#56]
There are still some codes called the print function the Python 2-way without the parentheses, which may raise SyntaxError in Python 3
here are some examples
```
except InvalidDocumentError:
       print 'Document is Invalid' 
       messages = []
       doc.validate(messages)
       print '\n'.join(messages)
```

**Comment by macrovve** [comment]
I think I can fix it, could I open a pull request for it.

**Comment by pombredanne** [comment]
Sure! go for it. A future import is the way to go for this.

**Comment by pombredanne** [comment]
Because we want to keep Python2 support

**Comment by mzfr** [comment]
@yash-nisar @pombredanne I wanted to know that there are lot's of open PR's but they were open a long time ago So can I work on them?
