### ISSUE TITLE
Example missing imports

### ISSUE THREAD

**Issue by stefan6419846** [spdx/tools-python#593]
I just started evaluating this project for generating SPDX files manually, but had some trouble to finally generate a custom document:

* The example at https://github.com/spdx/tools-python#example omits all imports.
* The example starts with parsing an existing file. As documentation is sparse anyway, this requires me to do quite some extra research on how to create a document itself manually.
* Instead of exposing the corresponding classes from the submodules of `spdx.models` inside `spdx/models/__init__.py`, I am required to import them from the corresponding submodules, which seems like some unnecessary overhead.

**Comment by armintaenzertng** [comment]
Thanks for the detailed feedback, Stefan, much appreciated! :)
As a first quick fix I opened a PR to include the imports in the readme example. I'll work on another example that demonstrates creating documents from scratch.

**Comment by armintaenzertng** [comment]
@stefan6419846, I have [created a new example file](https://github.com/spdx/tools-python/pull/598) that demonstrates how to create an SPDX document from scratch with this library. Please have a look and tell me if you find that helpful or where you wish for more information. :)

**Comment by stefan6419846** [comment]
Thanks, this is much appreciated to lower the burden of getting started with plain library usage.

Doing some further research in the package itself, I managed to write a similar example in the meantime (with the help of the actual specification), but good documentation does not hurt.

**Comment by armintaenzertng** [comment]
That's great to here! Please reach out if there are any more road blocks you encounter!
