### ISSUE TITLE
Make validation optional by introducing a `validate` flag

### ISSUE THREAD

**Issue by yash-nisar** [spdx/tools-python#60]
On the validation side, the validation will be an option. Fields will not be mandatory by default. They will be checked only when the user asks to validate and not at the time of creation. This will enforce the user to be able to create and dump eventually partial documents that may not yet be fully valid.

This can be established by introducing a `validate` flag in both the parsers (tagvalue and rdf) and validating only when the flag is set.

@pombredanne Should I create a PR for this one ?

**Comment by RishabhBhatnagar** [comment]
Hello there, this issue still persists??
If yes, I would like to resolve this.

**Comment by nicoweidner** [comment]
While the parser methods still don't have a `validate` flag (see e.g. [this section](https://github.com/spdx/tools-python/blob/7b9395589d65c117f541dc43e85895e2f6fb63ee/spdx/parsers/jsonparser.py#L27-L29)), there doesn't seem to be a lot of people impacted by this shortcoming. I will close this for the time being; the [upcoming refactoring](https://github.com/spdx/tools-python/issues/277) will validate in a separate layer anyway, and we can add a flag there.

Please ping if this should be reopened
