### ISSUE TITLE
Upgrade 'Document Creation Information' according to the 2.1 spec

### ISSUE THREAD

**Issue by yash-nisar** [spdx/tools-python#66]
Attributes to be added are: 
- [x] SPDX Identifier 
- [x] Document Name 
- [x] SPDX Document Namespace 
- [x] External Document References

See https://github.com/spdx/tools-python/pull/71.

**Comment by krysnuvadga** [comment]
@yash-nisar it will be nice if the issues are created with more detailed descriptions to them. For " Upgrade 'Document Creation Information' according to the 2.1 spec" is not enough to describe the entire task
