### ISSUE TITLE
ModuleNotFoundError: No module named 'spdx_tools'

### ISSUE THREAD

**Issue by grimace** [spdx/tools-python#677]
Can't seem to install and reference spdx-tools.
We've tried in a virtual venv and just straight up python3 environment like in the example.

` pip3 install spdx-tools`

but when we try to reference it we invariably get something like:

```
    from spdx_tools.spdx.model import (Checksum, ChecksumAlgorithm, File,
ModuleNotFoundError: No module named 'spdx_tools'

```
could there be a step we're missing?

**Comment by armintaenzertng** [comment]
I just noticed that the README "Installation" section does not state to use the alpha version. I'll fix this.
