### ISSUE TITLE
Understanding how to serialize relationships

### ISSUE THREAD

**Issue by willarmiros** [spdx/tools-python#681]
## Use case

I am trying to create a top-level `SpdxDocument` element using the `prototype-spdx-3.0` branch, which in turn will have (possibly transitive) relationships with several other elements. My ultimate goal is to serialize the `SpdxDocument` and all its related elements into a single JSON document. I know JSON serialization isn't supported yet, so I'm using the debug writer for now. Here's what my setup looks like:

```python
creation_info = CreationInfo(
    spec_version=Version("3.0.0"),
    created=datetime.now(),
    created_by=[agent_id],
    created_using=[tool_id],
    profile=[
        ProfileIdentifier.AI,
        ProfileIdentifier.DATASET,
        ProfileIdentifier.SOFTWARE,
    ],
)

doc_id = "SPDXRef-DOCUMENT"
doc = SpdxDocument(
    spdx_id=doc_id,
    name="SPDX MLBoM",
    creation_info=creation_info,
    description="Auto-generated Machine Learning Bill of Materials compliant with SPDX specification v3",
    element=[],
    root_element=[],
)

model_id = "SPDXRef-AIPackage"
pipeline = AIPackage(
    spdx_id=model_id,
    name=mlbom.model_name,
    creation_info=creation_info,
    supplied_by=[mlbom.owner],
    download_location=None,
    package_version=mlbom.version,
    purpose=[SoftwarePurpose.OTHER],
    description=mlbom.description,
    release_time=datetime.now(),
)

relationship_id = "SPDXRef-Relationship"
relationship = Relationship(
    spdx_id=relationship_id,
    from_element=doc_id,
    relationship_type=RelationshipType.DESCRIBES,
    to=[model_id],
)

doc.element = doc.element + [model_id, relationship_id]

# Would like this line to print out everything by itself, including Tool + Agent objects in CreationInfo!
spdx_document_writer.write_spdx_document(doc, sys.stdout)

ai_package_writer.write_ai_package(pipeline, sys.stdout)
relationship_writer.write_relationship(relationship, sys.stdout)
```

## Problem

1. While the above code does print the elements I asked, ideally I would expect the serializer to "traverse" the graph I've defined by relationships and serialize related elements too, so that I don't need to make an excessive number of calls to the writer.
2. The above code does NOT serialize the Tool and Agent objects that I reference by ID in the `creation_info` object. Should I define a relationship between them and the SpdxDocument so that this problem is the same as (1)? Or should there be some mechanism where all elements whose IDs are referenced in other properties get serialized?

Please stop me if this is all already well known and will be addressed with the JSON serializer! Just providing some feedback of how I would hope it to work as a user.

**Comment by armintaenzertng** [comment]
Hi @willarmiros, thanks for your interest in using the library! :)
There is an important conceptual difference between SPDX versions 2 and 3: While in v2 the SpdxDocument was the "top-level entity" that collected all elements in a serialized file, in v3 it is now simply another `Element` like for example `Package` or `Relationship`. The "entity" that collects all Elements from a single serialization file is now called `Payload`. You can find its implementation [here](https://github.com/spdx/tools-python/blob/1fc8cfffe9fea8d8d3843edbb734d721a15b30ae/src/spdx_tools/spdx3/payload.py). This is basically just a list of `Element` objects. Now, instead of writing every single object by itself, you add all objects you want to the payload and then write out the whole payload, using the [`write_payload()`](https://github.com/spdx/tools-python/blob/1fc8cfffe9fea8d8d3843edbb734d721a15b30ae/src/spdx_tools/spdx3/writer/console/payload_writer.py#L61) function.

As a side note: We merged the current state of the [json writer](https://github.com/spdx/tools-python/blob/1fc8cfffe9fea8d8d3843edbb734d721a15b30ae/src/spdx_tools/spdx3/writer/json_ld/json_ld_writer.py) yesterday, so try it out if you please (it also takes a `Payload` object)! :)
Note that if you are not interested in JSON-LD/RDF, you can just ignore the lengthy `@context` in the beginning of the serialized file. This will be replaced by a single URL once the context file is publicly available somewhere. The actual payload can be found under the `@graph` key.

**Comment by willarmiros** [comment]
Awesome, very helpful to know. I will use a Payload object and give the json writer a try and get back to this issue!

**Comment by willarmiros** [comment]
After some playing around, I have structured my BOM as such:

1. A payload that collects all elements, and is ultimately serialized into JSON-LD
2. A SpdxDocument element that acts as the root element in my element graph. Its `element` field contains an array of SPDX IDs of all other elements in the BoM, and its `rootElement` field is the SPDX ID of the SpdxDocument itself
3. All other elements (packages, files, datasets, etc) are either directly or transitively related to the SpdxDocument.

When I serialize the payload into JSON-LD, I get a BOM that looks reasonable to me! @armintaenzertng if you don't see any major issues with this approach, I'm happy to close the issue.

**Comment by armintaenzertng** [comment]
That sounds great, @willarmiros! If you don't mind, I would be interested to see the final result of yours. :)

Regarding the `rootElement` field, I don't think it is correct to put the SpdxDocument itself in there, see [this comment](https://github.com/spdx/spdx-3-model/issues/67#issuecomment-1422952046). According to this, `rootElement` should point to the Element(s) from which you can start traversing the hierarchy. This Element might be non-trivial to determine, though. As long as the field is required, we actually use the SpdxDocument as `rootElement`, too...

Also note that your point 3 is not a requirement for a payload. You can have Elements that are not part of the same hierarchy. You can even have multiple SpdxDocuments in a single serialization if you want (time will tell how often this feature is actually being used).

**Comment by willarmiros** [comment]
@armintaenzertng that's good to know on the rootElement, I think I can refactor it in a way where another element is the `rootElement`.  

> Also note that your point 3 is not a requirement for a payload

I know it's not a requirement, but in my case they are all part of the same hierarchy (for now at least). But if we run into a case in the future where we need separate hierarchies, it is good to know that I can adjust this if needed.

> I would be interested to see the final result of yours

I plan to do a very small demo at the AI + Data Profile meeting tomorrow, June 7, at 2pm PST. I'll also post a version of the SBOM on this issue if that timezone doesn't work!

**Comment by armintaenzertng** [comment]
Gary just put a clarifying comment in the issue: The `rootElement` should be the Elements that were DESCRIBED by the SpdxDocument in SPDX2.

2pm PST is 11pm CEST, I'll not be able to make that. ;)
I'd be glad to have a look at the SBOM if you post it here!

**Comment by willarmiros** [comment]
Saw that comment - makes things very clear! Will post the JSON here once I've made the update.

**Comment by willarmiros** [comment]
Here is a version of the final product! This SBOM models a ML pipeline. It includes a training dataset with a few files, an output model (as an AI Package), and 2 3rd party dependencies (originally had much more but I shortened it).

```json
{
  "@graph": [
    {
      "@type": "SpdxDocument",
      "@id": "protectai-SpdxDocument-brbr9384dNfPAH3WBCLUQd",
      "creationInfo": {
        "@type": "CreationInfo",
        "specVersion": "3.0.0",
        "created": "2023-06-06T16:24:18.585476Z",
        "createdBy": [
          "protectai-Organization-6WrkqBP8nu4jHXjhtXpmQu"
        ],
        "createdUsing": [
          "protectai-Tool-nmhatCKtcnxbX9D3NQwFhN"
        ],
        "profile": [
          "ai",
          "dataset",
          "software"
        ],
        "dataLicense": "CC0"
      },
      "name": "SPDX MLBoM",
      "description": "Auto-generated Machine Learning Bill of Materials compliant with SPDX specification v3",
      "element": [
        "protectai-Organization-6WrkqBP8nu4jHXjhtXpmQu",
        "protectai-Tool-nmhatCKtcnxbX9D3NQwFhN",
        "protectai-Relationship-CFUkqFbxQGKmWMqnwPuADw",
        "protectai-Dataset-QYMBB3BATVTERMvnqxPjHR",
        "protectai-S3FileElement-NZCLSBu3nodWrJNaxDaxHc",
        "protectai-S3FileElement-8CfhQxbbdFrjXaKzB762Kz",
        "protectai-S3FileElement-Vj8Qv24oGeMDwpG4nQB6ma",
        "protectai-Relationship-XjwN5t7xrU93ju2SNpPFtS",
        "protectai-S3FileElement-7zzZYpsx4rFqPRpAskzZEi",
        "protectai-Relationship-jD3KyWC4RN2CRmyQSdBYxH",
        "protectai-Relationship-DMNJrHhqUKzqf8BWiYzEcd",
        "protectai-Package-nmBwUNnQFCKuKdYbPKwRy3",
        "protectai-Package-kCZJxihYWtkQod7skLgDf2",
        "protectai-Relationship-JEiuboTqcjMBZoQvLGMfKQ"
      ],
      "rootElement": [
        "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s"
      ]
    },
    {
      "@type": "AIPackage",
      "@id": "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s",
      "name": "My first model",
      "description": "Test ability to log multiple artifacts",
      "suppliedBy": [
        "Data Science Team"
      ],
      "releaseTime": "2023-06-06T16:24:18.585541Z",
      "purpose": [
        "other"
      ],
      "packageVersion": "95da4bb2-62d4-4611-aa02-602e828dd4dc"
    },
    {
      "@type": "Organization",
      "@id": "protectai-Organization-6WrkqBP8nu4jHXjhtXpmQu",
      "name": "Protect AI",
      "description": "Easily Secure your AI & ML Systems",
      "externalReferences": [
        {
          "@type": "ExternalReference",
          "locator": [
            "https://protectai.com/"
          ]
        }
      ]
    },
    {
      "@type": "Tool",
      "@id": "protectai-Tool-nmhatCKtcnxbX9D3NQwFhN",
      "name": "Blah",
      "description": "SDK for Python"
    },
    {
      "@type": "Relationship",
      "@id": "protectai-Relationship-CFUkqFbxQGKmWMqnwPuADw",
      "from": "protectai-SpdxDocument-brbr9384dNfPAH3WBCLUQd",
      "to": [
        "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s"
      ],
      "relationshipType": "describes"
    },
    {
      "@type": "Dataset",
      "@id": "protectai-Dataset-QYMBB3BATVTERMvnqxPjHR",
      "name": "datasets",
      "originatedBy": [
        "Data Science Team"
      ],
      "builtTime": "2023-06-06T16:24:18.585798Z",
      "releaseTime": "2023-06-06T16:24:18.585799Z",
      "purpose": [
        "data"
      ],
      "downloadLocation": "See dataset files",
      "datasetType": "Unknown"
    },
    {
      "@type": "Package",
      "@id": "protectai-S3FileElement-NZCLSBu3nodWrJNaxDaxHc",
      "name": "data1.txt",
      "suppliedBy": [
        "s3"
      ],
      "purpose": [
        "file"
      ],
      "packageVersion": "pQH5zqDMSRNhaD9Ef7N8AMcWJpQ2aTNO",
      "downloadLocation": "s3://sdk-test/datasets/data1.txt",
      "packageUrl": "pkg:s3/sdk-test/datasets/data1.txt@pQH5zqDMSRNhaD9Ef7N8AMcWJpQ2aTNO"
    },
    {
      "@type": "Package",
      "@id": "protectai-S3FileElement-8CfhQxbbdFrjXaKzB762Kz",
      "name": "data2.txt",
      "suppliedBy": [
        "s3"
      ],
      "purpose": [
        "file"
      ],
      "packageVersion": "ltGogoakpFtsQDrlwILhE2vC8qicLZGY",
      "downloadLocation": "s3://sdk-test/datasets/data2.txt",
      "packageUrl": "pkg:s3/sdk-test/datasets/data2.txt@ltGogoakpFtsQDrlwILhE2vC8qicLZGY"
    },
    {
      "@type": "Package",
      "@id": "protectai-S3FileElement-Vj8Qv24oGeMDwpG4nQB6ma",
      "name": "data3.txt",
      "suppliedBy": [
        "s3"
      ],
      "purpose": [
        "file"
      ],
      "packageVersion": "GYqHPOdQc7J1SyDHd9Pzxs1k0OiVJ440",
      "downloadLocation": "s3://sdk-test/datasets/data3.txt",
      "packageUrl": "pkg:s3/sdk-test/datasets/data3.txt@GYqHPOdQc7J1SyDHd9Pzxs1k0OiVJ440"
    },
    {
      "@type": "Relationship",
      "@id": "protectai-Relationship-XjwN5t7xrU93ju2SNpPFtS",
      "from": "protectai-Dataset-QYMBB3BATVTERMvnqxPjHR",
      "to": [
        "protectai-S3FileElement-NZCLSBu3nodWrJNaxDaxHc",
        "protectai-S3FileElement-8CfhQxbbdFrjXaKzB762Kz",
        "protectai-S3FileElement-Vj8Qv24oGeMDwpG4nQB6ma"
      ],
      "relationshipType": "contains"
    },
    {
      "@type": "Package",
      "@id": "protectai-S3FileElement-7zzZYpsx4rFqPRpAskzZEi",
      "name": "newmodel.skops",
      "suppliedBy": [
        "s3"
      ],
      "purpose": [
        "file"
      ],
      "packageVersion": "L.GpMI7sMZ6u9MQhy0GatFqQ9sRVmB.Z",
      "downloadLocation": "s3://sdk-test/models/submodels/newmodel.skops",
      "packageUrl": "pkg:s3/sdk-test/models/submodels/newmodel.skops@L.GpMI7sMZ6u9MQhy0GatFqQ9sRVmB.Z"
    },
    {
      "@type": "Relationship",
      "@id": "protectai-Relationship-jD3KyWC4RN2CRmyQSdBYxH",
      "from": "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s",
      "to": [
        "protectai-S3FileElement-7zzZYpsx4rFqPRpAskzZEi"
      ],
      "relationshipType": "contains"
    },
    {
      "@type": "Relationship",
      "@id": "protectai-Relationship-DMNJrHhqUKzqf8BWiYzEcd",
      "from": "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s",
      "to": [
        "protectai-Dataset-QYMBB3BATVTERMvnqxPjHR"
      ],
      "relationshipType": "dependsOn"
    },
    {
      "@type": "Package",
      "@id": "protectai-Package-nmBwUNnQFCKuKdYbPKwRy3",
      "name": "GitPython",
      "suppliedBy": [
        "Sebastian Thiel, Michael Trier"
      ],
      "packageVersion": "3.1.30",
      "packageUrl": "pkg:pypi/gitpython@3.1.30"
    },
    {
      "@type": "Package",
      "@id": "protectai-Package-kCZJxihYWtkQod7skLgDf2",
      "name": "PyYAML",
      "suppliedBy": [
        "Kirill Simonov"
      ],
      "packageVersion": "6.0",
      "packageUrl": "pkg:pypi/pyyaml@6.0"
    },
    {
      "@type": "Relationship",
      "@id": "protectai-Relationship-JEiuboTqcjMBZoQvLGMfKQ",
      "from": "protectai-AIPackage-S9ZeXkw9udQAsvbC46tB4s",
      "to": [
        "protectai-Package-nmBwUNnQFCKuKdYbPKwRy3",
        "protectai-Package-kCZJxihYWtkQod7skLgDf2"
      ],
      "relationshipType": "dependsOn"
    }
  ]
}

```
