### ISSUE TITLE
[Bug] Sensor is required for Dataset object

### ISSUE THREAD

**Issue by willarmiros** [spdx/tools-python#682]
If I try to create a `Dataset` object using the `prototype-spdx-3.0` branch, and found that when you try to create one like so:

```python
ds = Dataset(
    spdx_id=dataset_id,
    creation_info=creation_info,
    name=dataset.name,
    dataset_type="text",
    originated_by=["s3"],
    download_location=os.getcwd(),
    purpose=[SoftwarePurpose.DATA],
    built_time=datetime.now(),
    release_time=datetime.now(),
)
```

It fails with the following error:

```
Traceback (most recent call last):
  File "/Users/williamarmiros/protectai-code/bom/spdx.py", line 110, in __init__
    ds = Dataset(
  File "/Users/williamarmiros/open-source/spdx/tools-python/src/spdx_tools/spdx3/model/dataset/dataset.py", line 100, in __init__
    check_types_and_set_values(self, locals())
  File "/Users/williamarmiros/open-source/spdx/tools-python/src/spdx_tools/common/typing/type_checks.py", line 37, in check_types_and_set_values
    raise ConstructorTypeErrors(errors)
spdx_tools.common.typing.constructor_type_errors.ConstructorTypeErrors: ['SetterError Dataset: argument "sensor" (None) is not a dict: None']
```

The problem is the `sensor` property cannot be a `None` type, which should be allowed by the spec. I will submit a PR to fix this tomorrow!

**Comment by armintaenzertng** [comment]
Good catch!
There is an excess "s" in `sensors` in [this line](https://github.com/spdx/tools-python/blob/c03912cabc5de41f64b571f532a018d5e76a1314/src/spdx_tools/spdx3/model/dataset/dataset.py#L97). If you like, go ahead and open a PR to fix this. :)

**Comment by willarmiros** [comment]
@armintaenzertng thanks for the pointer - opened a PR for the fix

**Comment by willarmiros** [comment]
Closing since PR is merged!
