### ISSUE TITLE
Getting validation error while running examples\spdx2_document_from_scratch.py

### ISSUE THREAD

**Issue by HarshvMahawar** [spdx/tools-python#692]
unable to follow the validation error in examples\spdx2_document_from_scratch.py
tried `document.files = [file1, file2]` , still no solution
<img width="768" alt="validation error" src="https://github.com/spdx/tools-python/assets/114311884/303d38d7-57af-4f06-9312-5a5ac7f9e1c3">

**Comment by armintaenzertng** [comment]
This has been fixed in #687 already, please pull the newest version :)

Nevertheless, to ensure that the examples will continue to work in the future, I opened a PR to add it as a test.
