### ISSUE TITLE
Remove spdx_licenselist.csv in favor of using spdx-lookup package

### ISSUE THREAD

**Issue by sschuberth** [spdx/tools-python#7]
Consider using the [spdx-lookup](https://pypi.python.org/pypi/spdx-lookup) package instead of the committed [spdx_licenselist.csv](https://github.com/spdx/tools-python/blob/master/spdx/spdx_licenselist.csv) file.

**Comment by pombredanne** [comment]
CSV is not great indeed. There is one issue though: package namespaces. Per https://github.com/bbqsrc/spdx-lookup-python/blob/4f5c2f540525421025e498289f9e84721683d7f9/spdx_lookup/__init__.py#L8 `spdx_lookup` from @bbqsrc depends on https://github.com/bbqsrc/spdx-python from the same author that provides the license lists proper but also uses the same `spdx` package namespace that this tool here is using. 

As such this could not be re-used as is unless we do on of these:

1. we vendor spdx-python
2. we rename the packages used here or there to distinct names
3. we adopt a shared package namespace strategy
4. we merge together

This is an issue I raised here https://github.com/bbqsrc/spdx-python/issues/1

**Comment by bbqsrc** [comment]
You can have the entire `spdx.*` namespace as long as the current interface of the `spdx` module can continue to exist, and the `spdx` package stays a minimal database package as it already is so it can be consumed by other projects.

If that works, then I'm open to any other suggestions. :smile:

**Comment by meretp** [comment]
Hi @sschuberth! We are cleaning up this repo and in the process I noticed this old issue. Since the linked repo has been archived and the CSV list is no longer part of the repo, I think this issue can be closed. 
Or are there any other ideas to rewrite the current use of the license list @pombredanne?

**Comment by sschuberth** [comment]
As 462e986daba28d6d9c28593dee29ff3d801a7268 replaced the CSV with the JSON from https://github.com/spdx/license-list-data/blob/master/json/licenses.json this can indeed be closed.
