### ISSUE TITLE
Is this organization name really invalid?

### ISSUE THREAD

**Issue by chrisdecker1201** [spdx/tools-python#721]
I'm getting the following error because of this Organization name:

~~~text
Organization: (c) Chris Sainty
~~~

The regex is the following:

~~~text
Organization:\s*(([^(])+)(\((.*)\))?
~~~

The documentation says the following:

~~~text
Organization: organization name and optional (<email>)
~~~

https://spdx.github.io/spdx-spec/v2.2.2/package-information/#76-package-originator-field

Should we update the regex inside this library, or is the organization name invalid?

**Comment by armintaenzertng** [comment]
Though rather vague, I don't think the spec marks `(c) Chris Sainty` as invalid.
This means our regex has to be adapted. Thanks for bringing this up! :)

**Comment by chrisdecker1201** [comment]
@armintaenzertng Could you/we reduce it just to the following regex?

~~~
^Organization:\s.+$
~~~

A whitespace followed by something.

**Comment by armintaenzertng** [comment]
We need to extract a potential email address from the string. That is, `Organization: (c) Chris Sainty (chris@sainty.com)` should parse into an `Actor` object with
```
actor_type = ActorType.Organization
name = "(c) Chris Sainty"
email = "chris@sainty.com"
```
Feel free to put up a PR with a regex that parses this; I myself would have to take a deeper look into the regex rabbit hole. ;)

**Comment by chrisdecker1201** [comment]
~~~text
^Organization:\s(?P<actor>[\[\](){}\w\s]+)(\s\((?P<email>.*)\))?$
~~~

This would be valid

~~~text
Organization: Acme [email]
Organization: (c) Chris Sainty (chris@sainty.com)
Organization: (c) Chris Sainty
Organization: (c) Chris Sainty1
Organization: HOMAG Group
Organization: HOMAG Group (info@homag.com)
Organization: ExampleCodeInspect ()
~~~

This would be invalid

~~~text
Organization: 
Organization: "Acme {email}"
Organization: 'Acme {email}'
~~~

Has someone a better idea? :)

**Comment by armintaenzertng** [comment]
Your proposed regex does not parse organization names that include special characters (like `/`, for example).
I'm also not sure that `"Acme {email}"` is actually an invalid name (I don't see how that follows from the spec).

I have a simpler proposal that actually matches everything until the last enclosing brackets:
```
^Organization:(?P<name>.*)\((?P<email>.*)\)$
```
`name` would need to be stripped of whitespaces after the parsing, but I think that would be all right.

**Comment by armintaenzertng** [comment]
@goneall, do you have any thoughts on this? Is the name discussed here actually valid or is it an oversight in the spec?

**Comment by armintaenzertng** [comment]
This does seem to do the trick:
```
^Organization:\s*(?:(.*)\((.*)\)|(.*))$
```
This either captures `name` in group 1 and `email` in group 2
OR
only `name` in group 3.

**Comment by zvr** [comment]
@armintaenzertng the one you suggested ah hour ago is almost fine. You just need to make the second part optional (surround it in parentheses and add the `?` operator afterwards):

    ^Organization:(?P<name>.*)(\((?P<email>.*)\))?$

The only thing to look out for is a complete empty value (nothing after "Organization:").

In any case, this is a moot point. The SPDXv2 spec never defined exactly the format of all these "structured" strings. Having something which is the same in Python and Java libraries is more important than getting the "right" answer, since there is none.

**Comment by armintaenzertng** [comment]
Thanks, @zvr, but your suggested regex does not seem to work as it doesn't parse anything into the "email" group.
The last one I posted seems to work, though, I opened a PR to prove it: #724. @chrisdecker1201, please have a look and see if this solves your case.
If you can think of more edge cases to test, feel free to post them! :)

**Comment by chrisdecker1201** [comment]
I think #724  is good. Thank you
