### ISSUE TITLE
Library Usage: Use of custom Licenses

### ISSUE THREAD

**Issue by arturrz** [spdx/tools-python#731]
I see there is support for adding `ExtractedLicensingInfo` to the document. However, how can one use those licenses when creating package objects? The package class licensing attributes only support: `LicenseExpression, SpdxNoAssertion, SpdxNone` types. I have some packages with licenses that are not on the SPDX License list, while adding the info for these using ExtractedLicensingInfo, I would also like to set these as LicenseConcluded for the related packages.

**Comment by armintaenzertng** [comment]
Hi @arturrz, thanks for the question! We handle `ExtractedLicensingInfo` and license expressions exactly like [described in the spec](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#101-license-identifier-field).
That is, every `ExtractedLicensingInfo` has a property `license_id`, for example `"LicenseRef-1"`, which can then be used in any `LicenseExpression` across the SPDX document, for example in the `license_concluded` property of a `Package`.
Note that you are not restricted to only use a single identifier in a license expression: `"LicenseRef-1 AND MIT"` would be a valid value for `license_concluded`, too, for example.

**Comment by arturrz** [comment]
Thanks for your input @armintaenzertng, I was able to use my custom license and documented it as described in the spec. My understanding was a bit off. 

On the other hand, I'd like to mention that I've been working on creating [SPDX Lite](https://spdx.github.io/spdx-spec/v2.2.2/SPDX-Lite/) documents due to industry needs and/or requirements. spdx-tools-java, does not provide this functionality either. Validation of these files results in error and there is no utility to support them. It'd be nice to add such feature since some industries might benefit from it. Let me know if I should submit a new issue with this proposal. Perhaps after v3 is fully supported by the tools there might be room for this. Cheers.

**Comment by armintaenzertng** [comment]
My understanding was that SPDX Lite is simply a subset of SPDX, so it should in principal be supported by the library.
Can you please provide an example SPDX document you would like to use and what validation errors are raised with it?

**Comment by armintaenzertng** [comment]
I believe this can be closed. Please reopen if you think differently.
