### ISSUE TITLE
Doubt regarding SPDX None value

### ISSUE THREAD

**Issue by HarshvMahawar** [spdx/tools-python#735]
in the spdx 2.3 specialization various fields suggests None when there is no value whatsoever, so is it None as in python datatype 'Nonetype' or SpdxNone class

**Comment by armintaenzertng** [comment]
I was under the impression that `NOASSERTION` is the default value in most cases, like [here](https://spdx.github.io/spdx-spec/v2.3/package-information/#713-concluded-license-field), for example.

In any case, in this repo a `NONE` from the specification is represented by `SpdxNone()`, while `NOASSERTION` would be `SpdxNoAssertion()`. If the value is simply not present, the python `NoneType` is used.

**Comment by HarshvMahawar** [comment]
okay, understood thanks :)

**Comment by armintaenzertng** [comment]
I believe this can be closed, please speak up if there is anything still left unclear! :)
