### ISSUE TITLE
Change order of properties when converting to json-dict

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#739]
As of python 3.7, we are able to determine the order of dictionary entries by the order of insertion.
This will reflect in the order of the keys in the resulting JSON document.

We should use this to sort the most important keys (SPDXID, name, etc) to the top.

**Comment by zvr** [comment]
I would suggest you use alphabetic ordering instead of an arbitrary "most important keys" order.

**Comment by armintaenzertng** [comment]
That would certainly be a valid approach, too.
The approach I described above came from a request by @rnjudge. Especially the intermingling of document information (like namespace, name etc) with other lists (like external licensing info etc) was a point of critique there.

I'm open to both approaches. Anyone has very strong opinions about this?

**Comment by armintaenzertng** [comment]
Closing this as there seems to be no real interest in this. Please reopen if you disagree.
