### ISSUE TITLE
List of possible errors returned from validation script

### ISSUE THREAD

**Issue by GriffinSchulte** [spdx/tools-python#741]
Is there is a list of possible errors that could be returned from running a document through the validation script?

**Comment by armintaenzertng** [comment]
Do you mean types of Python errors or the actual messages of the errors? The latter are generated dynamically using the input IDs, for example, so there is no fixed list of those. However, we might want to think about classifying these into specific groups.

What is your intended use case? Can you describe more specifically what information you want or what you want to do with it? If you already have something in mind, feel free to open a PR! :)

Thanks for the input and interest in the library!

**Comment by GriffinSchulte** [comment]
Hi there, Armin! I was just looking for the actual messages of the errors. I could walk through the collection of validation scripts myself and compile a rough list, but figured I'd check if one already existed :)

I'm building a wrapper around the _validate_full_spdx_document_ script specifically, intended to be used by clients that are less technically inclined, or simply for ease of use. The idea was the provide some end-user documentation to clients that would detail the error messages that might be returned, and how to fix them based on our needs.

Appreciate the quick reply!

**Comment by armintaenzertng** [comment]
Yes, all validation messages are contained in the `spdx.validation` package, so you could gather them there. This might be subject to change, though, as we only just released and users might find some holes in the validation.

If you think that the broader community could benefit from your improvements, we'd be glad to enhance the current code in the tools with some ideas of yours! :)

**Comment by armintaenzertng** [comment]
I believe this can be closed. Please reopen if you think differently.
