### ISSUE TITLE
External License reference is rejected by the validator

### ISSUE THREAD

**Issue by LeBlue** [spdx/tools-python#744]
A license expression of the form `DocumentRef-..:LicenseRef-..` is rejected by the validator but it should be accepted according to Annex D, both version 2.2 and 2.3.

The implementation does not consider the possibility of a external license reference. Subsequently the check for the correct declaration of the external document is missing.

**Comment by armintaenzertng** [comment]
Thank you very much for catching this, @LeBlue!
I opened a PR that should fix this issue, please have a look and review it if you like! :)
