### ISSUE TITLE
Error validating download location with git+ssh URI

### ISSUE THREAD

**Issue by bdehamer** [spdx/tools-python#745]
When using git URLs to reference packages in npm, the URL often gets normalized to a form like:

```
git+ssh://git@github.com/foo/bar.git#b7e1e0fb20cff47bcca4be90d0c6f83a45e51e9c
```

When using a URL of this form as a `downloadLocation` value, it fails validation due to the `git@` portion of the URL.

Can the URL regex be expanded to allow for the [`userinfo`](https://datatracker.ietf.org/doc/html/rfc2396#section-3.2.2) portion of the URI?

https://github.com/spdx/tools-python/blob/f15a64fdd3c2b889c613997fc35da908a794c607/src/spdx_tools/spdx/validation/uri_validators.py#L10-L12

**Comment by maxhbr** [comment]
Oh Yes, this should explicitly be allowed, see [spec section 7.7](https://spdx.github.io/spdx-spec/v2.3/package-information/#77-package-download-location-field).

We would also be happy to support you to contribute that fix. If you want, just start creating a PR. You already found the relevant code sesction.
