### ISSUE TITLE
Tags and format properties are case sensitive

### ISSUE THREAD

**Issue by vargenau** [spdx/tools-python#753]
The spec says: "Tags and format properties are case sensitive".

The document contains:
```
FilesAnalyzed: TRUE
```

pyspdxtools -i hello.spdx

ERROR:root:The document is invalid. The following issues have been found:
package must contain no elements if files_analyzed is False, but found [Relationship(spdx_element_id='SPDXRef-Package-hello', relationship_type=<RelationshipType.CONTAINS: 6>, related_spdx_element_id='SPDXRef-hello-binary', comment=None), Relationship(spdx_element_id='SPDXRef-Package-hello', relationship_type=<RelationshipType.CONTAINS: 6>, related_spdx_element_id='SPDXRef-Makefile', comment=None), Relationship(spdx_element_id='SPDXRef-Package-hello', relationship_type=<RelationshipType.CONTAINS: 6>, related_spdx_element_id='SPDXRef-hello-src', comment=None)]
license_info_from_files must be None if files_analyzed is False, but is: [LicenseSymbol('GPL-3.0-or-later', aliases=('GPL-3.0+', 'LicenseRef-GPL-3.0-or-later'), is_exception=False)]
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='9d20237bb72087e87069f96afb41c6ca2fa2a342', excluded_files=[])

The error message is misleading.

It should say that TRUE is not a correct value for FilesAnalyzed, instead of saying that FilesAnalyzed is False and outputing an error message assuming that FilesAnalyzed is false.

[hello.spdx.txt](https://github.com/spdx/tools-python/files/12538780/hello.spdx.txt)

**Comment by armintaenzertng** [comment]
This is an issue with the tag-value parsing, the corresponding code can be found [here](https://github.com/spdx/tools-python/blob/777bd274dd06cb24342738df7da5ab285d652350/src/spdx_tools/spdx/parser/tagvalue/parser.py#L430).

The code currently does not check whether the input is conformant with the spec at all. This should be added.

As this is simply a boolean, I don't think we should be as strict as the spec suggests and instead accept `True` or `TRUE` as valid input, too.

**Comment by maxhbr** [comment]
> ... I don't think we should be as strict as the spec suggests ...

I think we should be as strict and instead fail with an helpful error if some value can not be parsed to bool.

**Comment by vargenau** [comment]
I agree with Max. We should follow the standard and be strict.

**Comment by armintaenzertng** [comment]
@vargenau, I opened #758 to address the issue, please have a look and see if this solves your problem.

**Comment by vargenau** [comment]
Hello @armintaenzertng

I confirm #758 fixes the issue.
Thank you for the quick fix.
