### ISSUE TITLE
Conversion from JSON tag:value gives invalid SPDX

### ISSUE THREAD

**Issue by vargenau** [spdx/tools-python#754]
hello.spdx.json contains:
```
"filesAnalyzed": true,
```

Converting from JSON to tag:value

hello.spdx contains:
```
FilesAnalyzed: True
```
that is invalid as tags and format properties are case sensitive.

[hello.spdx.json.txt](https://github.com/spdx/tools-python/files/12539153/hello.spdx.json.txt)
[hello.spdx.txt](https://github.com/spdx/tools-python/files/12539154/hello.spdx.txt)

**Comment by armintaenzertng** [comment]
Correct, tag-value should have `true` and `false` in lower-case [according to the spec](https://spdx.github.io/spdx-spec/v2.3/package-information/#78-files-analyzed-field).

**Comment by armintaenzertng** [comment]
@vargenau, please have a look if #757 solves your problem.

**Comment by vargenau** [comment]
Hello @armintaenzertng

I confirm #757 fixes the issue.
Thank you for the quick fix.
