### ISSUE TITLE
Encoding in `parse_file` method

### ISSUE THREAD

**Issue by chrisdecker1201** [spdx/tools-python#755]
I'm having an issue because of a different encoding in the `parse_file` method.

Is there a reason why you just call `open` without encoding?

Otherwise I would prepare a PR for that.

**Comment by goneall** [comment]
Just FYI - The spec states the the files are encoded as UTF-8 in [section 4.4](https://spdx.github.io/spdx-spec/v2.3/conformance/#44-standard-data-format-requirements).

**Comment by chrisdecker1201** [comment]
Should we than revert the change and set the encoding fixed to UTF-8?

**Comment by goneall** [comment]
@chrisdecker1201 I don't have much insight into the internals of the tools-python to comment on the specific code changes, but here's a couple thoughts and opinions on the functionality:

- I would only make it an option on reading, writing should always follow the standard UTF-8 encoding
- It isn't uncommon to run across incorrectly encoded SPDX files, so there is value to having an option
- UTF-8 should definitely be a default if it is an option in the API
- If we do make it an option on parsing, it would be good if the validator reported a warning that it was encoded in something other than the standard.
- If we do make it an option on parsing, it would be nice to document the API that the standard is UTF-8

**Comment by chrisdecker1201** [comment]
If the following suggestions are okay for you, I can prepare another PR.

* set `parse_file` encoding from `None` to `utf-8`

* bring a warning if someone set `encoding` to something else than `utf-8`: "It's recommanded to use the `UTF-8` encoding for any SPDX file. Consider changing the encoding of the file." I think it's easier to check the `encoding` parameter then checking the encoding of the file, due to this stackoverflow entry: https://stackoverflow.com/a/436299/6690188

    *Correctly detecting the encoding all times is impossible.*

* set the `encoding` to `UTF-8` of any `write_document_to_file` method

**Comment by armintaenzertng** [comment]
@chrisdecker1201, sounds good to me! :)

**Comment by goneall** [comment]
> If the following suggestions are okay for you, I can prepare another PR.
> 
> * set `parse_file` encoding from `None` to `utf-8`
> * bring a warning if someone set `encoding` to something else than `utf-8`: "It's recommanded to use the `UTF-8` encoding for any SPDX file. Consider changing the encoding of the file." I think it's easier to check the `encoding` parameter then checking the encoding of the file, due to this stackoverflow entry: https://stackoverflow.com/a/436299/6690188
>   _Correctly detecting the encoding all times is impossible._
> * set the `encoding` to `UTF-8` of any `write_document_to_file` method

Sounds good to me too - thanks @chrisdecker1201
