### ISSUE TITLE
Unable to parse https://git.causal.agency/libretls/  as downloadLocation

### ISSUE THREAD

**Issue by pushkargr** [spdx/tools-python#761]
Tool is failing to parse the downloadLocation in the following format:
`https://git.causal.agency/libretls/`

Following is the error:
`package download_location must be a valid download location according to the specification, but is: https://git.causal.agency/libretls/`

Is this expected to not support this URL format?

**Comment by armintaenzertng** [comment]
Good catch! The spec supports arbitrary URLs while the implementation in this library only checks for the more specialized VCS location syntax.

**Comment by maxhbr** [comment]
same as https://github.com/spdx/tools-python/issues/762
