### ISSUE TITLE
Tool is failing to parse URL like git@github.com:siimon/prom-client.git in downloadLocation

### ISSUE THREAD

**Issue by pushkargr** [spdx/tools-python#762]
URL like git@github.com:siimon/prom-client.git are valid download locations. Github provides the link this way. But the tool is marking this as invalid.

`package download_location must be a valid download location according to the specification, but is: git@github.com:siimon/prom-client.git`

![image](https://github.com/spdx/tools-python/assets/19174297/af592123-09b3-4cce-9957-dbee2ec1445a)

Could the specification be incorrect in this case and the tool should be able to adjust it?

**Comment by maxhbr** [comment]
[Not sure what the specification says about that](https://spdx.github.io/spdx-spec/v2.3/package-information/#77-package-download-location-field). Download Location is either a URL or a "VCS location", where the "VCS location" is of the following form:
```
<vcs_tool>+<transport>://<host_name>[/<path_to_repository>][@<revision_tag_or_branch>][#<sub_path>]
```
Not sure if that example falls under URL or "VCS location", but the VCS Location seems to always contain `://`.

On the other hand, the specification has the example `git+git@git.myproject.org:MyProject` which is close to your form.

**Comment by maxhbr** [comment]
Just checked https://validator.w3.org/checklink?uri=git%40github.com%3Asiimon%2Fprom-client.git&hide_type=all&depth=&check=Check and the download location you want to use is not a valid URL and fails with `error Error: 400 URL must be absolute`
