### ISSUE TITLE
IndexError on parsing failure

### ISSUE THREAD

**Issue by bmihaila-synopsys** [spdx/tools-python#764]
When parsing this file https://github.com/chainguard-dev/bom-shelter/blob/main/in-the-lab/spdx-popular-containers/data/spdx-trivy-vmware_log-intelligence-fluentd-sha256%3A086af034f561f343f633be9d9f9e95f65ae6c61b8ddb2c6755ef5bb25b40f53a.json there is a parsing error with licenses. However, when trying to create and raise an SPDXParsingError the library bugs itself with IndexError. See below:
```
File \".../site-packages/spdx_tools/spdx/parser/jsonlikedict/dict_parsing_functions.py\", line 31, in parse_field_or_log_error
return parsing_method(field)
           ^^^^^^^^^^^^^^^^^^^^^
File \.../site-packages/spdx_tools/spdx/parser/jsonlikedict/license_expression_parser.py\", line 23, in parse_license_expression
raise SPDXParsingError([f\"Error parsing LicenseExpression: {err.args[0]}: {license_expression_str}\"])
                                                                ~~~~~~~~^^^\nIndexError: tuple index out of range"}
```

**Comment by maxhbr** [comment]
Thanks for pointing out that our logic to generate the parsing errors has a bug.

As related information, the following error gets thrown by the online tools:
![2023-09-27_08-42-38](https://github.com/spdx/tools-python/assets/1187050/5b66e23a-bec1-4117-8e07-4ee73a62bcc1)
