### ISSUE TITLE
Relationship with Package Section

### ISSUE THREAD

**Issue by jblu42** [spdx/tools-python#797]
I got a problem parsing some SBOMs created by another tool. This other tool puts the relationship within the Package section after the PackageSupplier field (the relationship of this individual package). For the next Package the relationship again is in the Package section.

I get this error when trying to parse the file:
spdx_tools.spdx.parser.error.SPDXParsingError: ["Error while constructing Package: __init__() missing 1 required positional argument: 'download_location'", 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 18', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 19', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 20', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 21', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 22', "Error while constructing Package: __init__() missing 1 required positional argument: 'download_location'", 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 31', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 32', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 33', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 34', 'Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 35']

I found no reason in the spec, why this should not be valid, but maybe I missed something? Or is this just a parsing error by the library?

If I put all relationship information either on the top or bottom of the file, it can be parsed without any problems.
[not_working_relationship.txt](https://github.com/spdx/tools-python/files/14223585/not_working_relationship.txt)
[working_relationship.txt](https://github.com/spdx/tools-python/files/14223586/working_relationship.txt)

**Comment by meretp** [comment]
Hi @jblu42, 
there is acutally a section in the spec explaining that this is not valid, see the following link, especially the last bulletpoint  https://spdx.github.io/spdx-spec/v2.3/composition-of-an-SPDX-document/#522-package-information-section 

The parser fails in your case as the placement of the relationship somehow interrupts the package section and the parser thinks that there is a package which is missing the required field "download_location" and for the fields coming after the "disruptive" relationship it is missing a package name as this is the field which denotes a new package. Hope this helps to understand the error message you get.
To solve this issue the tooling you are using could add the relationship after the package information section like below or as you also stated it can group the relationship information on the top or bottom of the file.
```
## Document Header
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: Demo_SBOM
DocumentNamespace: http://demosbom
Creator: Organization: My Demo Company
Creator: Person: John Doe
Created: 2023-11-14T11:09:04Z
      
## Packages
## 2.4 Primary Component (described by the SBOM)
PackageName: Primary Component Name
SPDXID: SPDXRef-Primary-Component
PackageVersion: 4.30.0015
PackageSupplier: Organization: My Demo Company 
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Primary-Component
  
## 2.4 All-Levels Components
##
PackageName: UltraModernUI
SPDXID: SPDXRef-Package13452
PackageVersion: 2.0b6
PackageSupplier: Organization: NOASSERTION 
PackageDownloadLocation: https://github.com/SuperPat45/UltraModernUI/archive/2.0b6.tar.gz
FilesAnalyzed: false
PackageLicenseConcluded: Zlib
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
Relationship: SPDXRef-Primary-Component CONTAINS SPDXRef-Package13452
```

**Comment by jblu42** [comment]
@meretp: Thanks for the clarification. I will try to contact the responsible for the other tool as it seems to violate the spec.
