### ISSUE TITLE
has_optional_field implementation may lead to unexpected results

### ISSUE THREAD

**Issue by xavierfigueroav** [spdx/tools-python#88]
_has_optional_field(field)_ verifies whether the value of _field_ is not None. But, some attributes are sometimes initialized as some default/empty object, like an empty list. In that example, _has_optional_field(field)_ will always return True, even if the list is empty (when I think it should return False because there is actually no information).

I suggest: return bool(field)

**Comment by b-thebest** [comment]
Can I work on this issue ?
