### ISSUE TITLE
parse_tv.py causes version issues

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-python#89]
While running example codes in how to use section of [https://github.com/spdx/tools-python](README.md),   
  
Running  
```python parse_tv.py '../data/SPDXSimpleTag.tag'   ```
gives following error:

```
Generating LALR tables  
SPDXVersion must be SPDX-1.2 found SPDX-2.1.  
Errors encountered while parsing
```

**Comment by pombredanne** [comment]
@RishabhBhatnagar good find. PR welcomed

**Comment by pombredanne** [comment]
actually there are pending PRs by @yash-nisar but they need to be rebased before I can merge them... May be that something you can have a look into (unless @yash-nisar can handle it?)

**Comment by omi10859** [comment]
Is it still open? Someone already working?

**Comment by krysnuvadga** [comment]
@omi10859 you can take on it

**Comment by omi10859** [comment]
seem to be working with no errors 
![Screenshot 2019-04-15 at 1 12 09 AM](https://user-images.githubusercontent.com/26123416/56098184-8284ae80-5f1b-11e9-853a-fdbcecbede6f.png)

@RishabhBhatnagar can you brief on how to regenerate the error?

**Comment by krysnuvadga** [comment]
@RishabhBhatnagar I am closing this issue in favor that no one has reproduced thesame error as a bug
